software_paths:
  bwa_dir: "/home/smuabdullah/1_Files/bwa-0.7.17"
  samtools_dir: "/home/smuabdullah/1_Files/EEX101/samtools-1.8"
  anaconda_dir: "/home/smuabdullah/1_Files/Anaconda3/bin"
  matlab_dir: "/usr/local/MATLAB/R2021b"
  mafft_dir: "/home/smuabdullah/1_Files/MAFFT/bin"
