software_paths:
  bwa_dir: "/path/to/bwa-0.7.17"
  samtools_dir: "/path/to/samtools-1.8"
  anaconda_dir: "/path/to/Anaconda3/bin"
  matlab_dir: "/path/to/MATLAB/R2021b"
  mafft_dir: "/path/to/MAFFT/bin"
